"""Judgment-core exports for the next architecture step."""

from comp.judgment.commit import (
    DraftSnapshot,
    PublicOutput,
    PublicOutputBlocked,
    blocking_hazards_clear,
    build_public_output,
    committable,
    prov_enough,
    resolved_required_bundles,
)
from comp.judgment.core import Fact, FactTag, JudgmentState, SubjectKind, SubjectRef
from comp.judgment.engine import FixpointEngine
from comp.judgment.frontier import (
    CandidateSummary,
    dominates,
    frontier,
    needs_review,
    winner_or_none,
)
from comp.judgment.program import (
    BundleSpec,
    CommitSpec,
    CompiledJudgmentProgram,
    PublicOutputSpec,
    TransferEmitter,
    TransferRule,
)
from comp.judgment.receipts import (
    DependencyFingerprint,
    PublicOutputReceipt,
    PublicOutputReceiptCitations,
    PublicOutputValueCommitment,
    SelectionReceipt,
)
from comp.judgment.receipt_authenticity import (
    MalformedReceiptSignature,
    ReceiptAuthenticityError,
    ReceiptIssuer,
    ReceiptKeyRegistry,
    ReceiptSignature,
    ReceiptVerificationResult,
    SignedPublicOutputReceipt,
    UnknownReceiptIssuer,
    UnsupportedReceiptSignatureAlgorithm,
    public_output_receipt_signed_body,
    public_output_receipt_signed_body_digest,
    verify_public_output_receipt,
)

__all__ = [
    "SubjectKind",
    "FactTag",
    "SubjectRef",
    "Fact",
    "JudgmentState",
    "TransferEmitter",
    "TransferRule",
    "BundleSpec",
    "CommitSpec",
    "PublicOutputSpec",
    "CompiledJudgmentProgram",
    "FixpointEngine",
    "CandidateSummary",
    "dominates",
    "frontier",
    "winner_or_none",
    "needs_review",
    "DraftSnapshot",
    "PublicOutput",
    "PublicOutputBlocked",
    "resolved_required_bundles",
    "blocking_hazards_clear",
    "prov_enough",
    "committable",
    "build_public_output",
    "SelectionReceipt",
    "PublicOutputValueCommitment",
    "DependencyFingerprint",
    "PublicOutputReceipt",
    "PublicOutputReceiptCitations",
    "ReceiptAuthenticityError",
    "UnknownReceiptIssuer",
    "UnsupportedReceiptSignatureAlgorithm",
    "MalformedReceiptSignature",
    "ReceiptKeyRegistry",
    "ReceiptIssuer",
    "ReceiptSignature",
    "SignedPublicOutputReceipt",
    "ReceiptVerificationResult",
    "public_output_receipt_signed_body",
    "public_output_receipt_signed_body_digest",
    "verify_public_output_receipt",
]
