"""Comp-backed product facade observation lab."""

from examples.product_facade_lab.bundle import (
    verify_verification_bundle,
    verify_verification_bundle_file,
    verification_input_from_bundle,
    verification_input_to_bundle,
)
from examples.product_facade_lab.runner import (
    CONFORMANCE_CASES_SCHEMA_VERSION,
    VerificationBundleCaseResult,
    VerificationBundleFixtureResult,
    VerificationBundleSuiteResult,
    run_all_fixtures,
    run_case_manifest,
    run_case_manifest_summary,
    run_conformance_cases,
    run_fixture,
    summarize_conformance_results,
)
from examples.product_facade_lab.runtime import (
    ArtifactTouchLog,
    ArtifactTouchLogComparison,
    CompCompatibleVerificationInput,
    CompVerificationOutput,
    ProductAudit,
    ProductFacadeRuntime,
    ProductInput,
    ProductPolicyPreflightInput,
    ProductPublicRow,
    ProductRequiredAction,
    ProductRun,
    ProductWitness,
    compare_touch_logs,
    verify_comp_compatible_input,
)

__all__ = [
    "ArtifactTouchLog",
    "ArtifactTouchLogComparison",
    "CONFORMANCE_CASES_SCHEMA_VERSION",
    "CompCompatibleVerificationInput",
    "CompVerificationOutput",
    "ProductAudit",
    "ProductFacadeRuntime",
    "ProductInput",
    "ProductPolicyPreflightInput",
    "ProductPublicRow",
    "ProductRequiredAction",
    "ProductRun",
    "ProductWitness",
    "VerificationBundleCaseResult",
    "VerificationBundleFixtureResult",
    "VerificationBundleSuiteResult",
    "compare_touch_logs",
    "run_all_fixtures",
    "run_case_manifest",
    "run_case_manifest_summary",
    "run_conformance_cases",
    "run_fixture",
    "summarize_conformance_results",
    "verify_comp_compatible_input",
    "verify_verification_bundle",
    "verify_verification_bundle_file",
    "verification_input_from_bundle",
    "verification_input_to_bundle",
]
