"""Active package surface for the comp rebuild branch.

The top-level package intentionally exposes the judgment-core surface only.
Legacy pipeline runners and pass-pipeline modules live in the archive snapshot;
they are no longer active package source.
"""

from comp.judgment import (
    BundleSpec,
    CandidateSummary,
    CommitSpec,
    CompiledJudgmentProgram,
    DependencyFingerprint,
    DraftSnapshot,
    Fact,
    FactTag,
    FixpointEngine,
    JudgmentState,
    PublicOutput,
    PublicOutputBlocked,
    PublicOutputReceipt,
    PublicOutputReceiptCitations,
    PublicOutputSpec,
    PublicOutputValueCommitment,
    MalformedReceiptSignature,
    ReceiptAuthenticityError,
    ReceiptIssuer,
    ReceiptKeyRegistry,
    ReceiptSignature,
    ReceiptVerificationResult,
    SelectionReceipt,
    SignedPublicOutputReceipt,
    SubjectKind,
    SubjectRef,
    TransferEmitter,
    TransferRule,
    UnknownReceiptIssuer,
    UnsupportedReceiptSignatureAlgorithm,
    blocking_hazards_clear,
    build_public_output,
    committable,
    dominates,
    frontier,
    needs_review,
    prov_enough,
    public_output_receipt_signed_body,
    public_output_receipt_signed_body_digest,
    resolved_required_bundles,
    verify_public_output_receipt,
    winner_or_none,
)

__all__ = [
    "SubjectKind",
    "FactTag",
    "SubjectRef",
    "Fact",
    "JudgmentState",
    "TransferEmitter",
    "TransferRule",
    "BundleSpec",
    "CommitSpec",
    "PublicOutputSpec",
    "CompiledJudgmentProgram",
    "FixpointEngine",
    "CandidateSummary",
    "dominates",
    "frontier",
    "winner_or_none",
    "needs_review",
    "DraftSnapshot",
    "PublicOutput",
    "PublicOutputBlocked",
    "resolved_required_bundles",
    "blocking_hazards_clear",
    "prov_enough",
    "committable",
    "build_public_output",
    "SelectionReceipt",
    "PublicOutputValueCommitment",
    "DependencyFingerprint",
    "PublicOutputReceipt",
    "PublicOutputReceiptCitations",
    "ReceiptAuthenticityError",
    "UnknownReceiptIssuer",
    "UnsupportedReceiptSignatureAlgorithm",
    "MalformedReceiptSignature",
    "ReceiptKeyRegistry",
    "ReceiptIssuer",
    "ReceiptSignature",
    "SignedPublicOutputReceipt",
    "ReceiptVerificationResult",
    "public_output_receipt_signed_body",
    "public_output_receipt_signed_body_digest",
    "verify_public_output_receipt",
]
